# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fusviz"
description: "Heavily tailored from ARRIBA's original script draw_fusions.R to fit RNAinn s fusion file"
keywords:
  - fusions
  - visualization
  - rna
tools:
  - "fusviz":
      description: "Fast and accurate gene fusion visualization from RNA-Seq data"
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ['MIT']
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - normal_bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_2572"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
    - bam_tumour:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_2572"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
    - tsv:
        type: file
        description: Fusions input file
        pattern: "*.{tsv}"
        ontologies:
          - edam: "http://edamontology.org/format_3475"
    - gtf:
        type: file
        description: Annotations file
        pattern: "*.{gtf}"
        ontologies:
          - edam: "http://edamontology.org/format_2306"
    - genome:
        type: string
        description: Reference genome
    - cytobands:
        type: file
        description: Cytobands file
        pattern: "*.{tsv}"
        ontologies:
          - edam: "http://edamontology.org/format_3475"
    - protein_domains:
        type: file
        description: Protein Domains file
        pattern: "*.{gff3}"
        ontologies:
          - edam: "http://edamontology.org/format_1975"
output:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - pdf:
        type: file
        description: Fusion visualization file in PDF format
        pattern: "*.pdf"
        ontologies:
          - edam: "http://edamontology.org/format_3508"
  - - versions:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@jblancoheredia <blancoj@mskcc.org>"
maintainers:
  - "@jblancoheredia <blancoj@mskcc.org>"