name: "iannotatesv"
description: Annotate structural variants using iAnnotateSV
keywords:
  - annotation
  - structural variants
  - genomics
tools:
  - "iannotatesv":
      description: Tool for annotation and visualization of structural variants
      homepage: https://github.com/rhshah/iAnnotateSV
      documentation: https://github.com/rhshah/iAnnotateSV
      tool_dev_url: https://github.com/rhshah/iAnnotateSV
      licence: ["Apache License 2.0"]
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - filtered_vcf:
      type: file
      description: Filtered VCF file
      pattern: "*.vcf"
  - filtered_vcf_index:
      type: file
      description: Index file for the filtered VCF
      pattern: "*.tbi"
  - filtered_tsv:
      type: file
      description: Filtered TSV file
      pattern: "*.tsv"
  - annote_input:
      type: file
      description: Input file for annotation
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - txt:
      type: file
      description: Annotated text file
      pattern: "*_Annotated.txt"
  - json:
      type: file
      description: Annotated JSON file
      pattern: "*_Annotated.json"
  - xlsx:
      type: file
      description: Annotated Excel file
      pattern: "*_Annotated.xlsx"
  - ftxt:
      type: file
      description: Functional annotation text file
      pattern: "*_functional.txt"
  - tsv:
      type: file
      description: Somatic SV output TSV file
      pattern: "*_SOMTIC_SV_OUT.tsv"
  - ann:
      type: file
      description: Somatic SV annotation TSV file
      pattern: "*_SOMTIC_SV_ANN.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@rhshah"
maintainers:
  - "amoahk1@mskcc.org"
  - "@jblancoheredia"